### ISSUE TITLE
RoverCam only works on  (0.9.0)

### ISSUE THREAD

**Issue by jtoy** [freshfork/p5.RoverCam#1]
I tried with all versions after 0.9.0 (0.10.2, 0.10.0 1.0.0) and I get this error:
"Uncaught ReferenceError: registerMethod is not defined"
but it works on older versions (0.9.0) of p5js.

**Comment by jtoy** [comment]
I tried changing the code to "p5.prototype.registerMethod('post',  () => this.draw())", ,that makes the error go away, but then the plugin doesnt work, you cant control the camera

**Comment by jwdunn1** [comment]
I'm not sure what happened to registerMethod in the newer versions of p5, but here is a workaround. Comment the call to registerMethod and add a callback to the RoverCam instance draw method within the main draw loop. For example: https://editor.p5js.org/jwdunn1/sketches/Y3hSXDfmw
Look for the comment "WORKAROUND" in sketch.js and p5.RoverCam.js

**Comment by jtoy** [comment]
Yes, that does seem to work. I'll try to look around the p5js plugin system, I've never used that, but would be good to learn.   1 thing I noticed, in all the rover demos I tested, the "d" key/right movement doesn't seem to work. Do you experience that as well?

**Comment by jwdunn1** [comment]
Hmm. "d" key is working for me. In the example sketch I provided earlier, be sure to click at least once on the canvas (to set the focus) before using the keyboard.

**Comment by jtoy** [comment]
weird, I tested it several times before and read through the code, but on testing it again, it works, thanks!

**Comment by jwdunn1** [comment]
I've updated the master branch for compatibility with all versions of p5. (better operation of registerMethod) Let me know if the new library code works correctly for you _without the workaround_ on any version of p5.

**Comment by jwdunn1** [comment]
This issue should be fixed for all versions of p5.
