### ISSUE TITLE
How can the license be MIT if QueasyCam is GPL?

### ISSUE THREAD

**Issue by RobinBoers** [freshfork/p5.RoverCam#6]
The LICENSE document in this repo says the code is distributed under the terms of the MIT license, however the source code says this is a derivative of QueasyCam, which is licensed under the terms of the GPL. If I'm not mistaken, the GPL requires any derivative works to also be licensed GPL?

I really want to use this library but my code is licensed Unlicense (public domain), which wouldn't be compatible with the GPL. Is this a fork of QueasyCam (and thus GPL licensed) or just inspired by QueasyCam (and thus MIT licensed)?

**Comment by jwdunn1** [comment]
Thanks for asking. p5.RoverCam (JavaScript) was inspired by QueasyCam (Java) and written from the ground up with additional features as an MIT licensed p5.js library to extend the functionality of p5.js. 
FYI, p5.js is licensed under LGPL 2.1
